// RootLayout.js
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-gradient-to-t from-zinc-950 to-blue-950 flex flex-col min-h-screen'>
        <Header/>
        {children}
      </body>
    </html>
  );
}
